# Generated by Django 5.2.4 on 2025-07-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lekalgroupapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=2, upload_to='product_images', verbose_name='Məhsul şəkli'),
            preserve_default=False,
        ),
    ]
