# Generated by Django 5.2.4 on 2025-07-23 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lekalgroupapp', '0002_product_is_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Ana səhifədə olacaq seçili məhsul'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lekalgroupapp.product', verbose_name='Məhsul'),
            preserve_default=False,
        ),
    ]
