# Generated by Django 5.2.4 on 2025-07-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lekalgroupapp', '0004_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
