# Generated by Django 5.2.4 on 2025-07-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lekalgroupapp', '0005_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ad')),
                ('logo', models.ImageField(blank=True, upload_to='logo_images/', verbose_name='Əməkdaş logo şəkli')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Əməkdaş',
                'verbose_name_plural': 'Əməkdaşlar',
            },
        ),
    ]
