# Generated by Django 5.2.4 on 2025-07-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lekalgroupapp', '0007_partner_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='about',
            field=models.TextField(default='', max_length=250, verbose_name='Əməkdaş haqqında'),
            preserve_default=False,
        ),
    ]
