# Generated by Django 5.2.4 on 2025-07-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lekalgroupapp', '0008_partner_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='about',
        ),
    ]
