# Generated by Django 5.2.4 on 2025-07-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lekalgroupapp', '0009_remove_partner_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Məhsul aktivliyi'),
        ),
    ]
