# Generated by Django 5.2.4 on 2025-07-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lekalgroupapp', '0010_category_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
    ]
