# Generated by Django 5.2.4 on 2025-07-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lekalgroupapp', '0012_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
