# Generated by Django 5.2.4 on 2025-07-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lekalgroupapp', '0013_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='product_images', verbose_name='Məhsul şəkli'),
        ),
    ]
